### ISSUE TITLE
Unable to access settings

### ISSUE THREAD

**Issue by thehamish555** [doggybootsy/enhancecodeblocks#6]
Attempting to open the settings tab shows this screen, and clicking to retry does nothing, Using version released earlier today
![image](https://github.com/doggybootsy/enhancecodeblocks/assets/89168856/11367fee-a4b5-4e42-8885-e2c44d3cba93)

**Comment by doggybootsy** [comment]
I'll look into this tomorrow. I didn't even think about that when I pushed the fix earlier

**Comment by doggybootsy** [comment]
Fixed, i forgot about this yesterday

**Comment by thehamish555** [comment]
Ive updated the plugin but the error remains? I also fully reinstalled the plugin

**Comment by doggybootsy** [comment]
Did you download it from github?

**Comment by thehamish555** [comment]
Yes

**Comment by doggybootsy** [comment]
huh, seems like they changed something right after i pushed a fix

**Comment by doggybootsy** [comment]
Fixed the issue, i was using a module that was lazy loaded
